open_router_api_key = ""
hyperbolic_api_key = ""
open_ai_api_key = ""
email = ""
email_password = ""
x_username = ""
x_password = ""
eth_rpc_url = ""
kv_db_path = ""
min_storing_memory_score = 2
min_posting_score = 3
max_num_mentions = 50
max_timeline_tweets = 50
num_long_term_memories = 5
num_recent_posts = 5
# in seconds when do you want to the bot run before handing over the account credentials
release_credentials = 604800
