open_router_api_key=""
hyperbolic_api_key=""
open_ai_api_key=""
x_consumer_key=""
x_consumer_key_secret=""
x_access_token=""
x_access_token_secret=""
x_client_id=""
x_client_secret=""
eth_rpc_url=""
x_api_url=""
hyperbolic_api_url=""
open_ai_api_url="https://api.openai.com/v1"
x_username=""
kv_db_path=""
min_storing_memory_score=2
min_posting_score=3
